services:
  - type: web
    name: pdf-house
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_PORT
        value: 5000
      - key: TEMP_DIR
        value: /tmp/pdf_temp
